version: '3'

networks:
  default:
    driver: bridge

services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    container_name: web
    volumes:
      - ./:/app:consistent
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - PHP_IDE_CONFIG=serverName
      - PHP
    ports:
      - '80:80'
    networks:
      - default
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_DATABASE=twapi
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=password1
      - MYSQL_ROOT_PASSWORD=rootpassword1
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8888:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db